version: '3'
services:
  # php
  composer-phpunit:
    image: composer:2.6.5
    restart: on-failure
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - ./app:/app
    working_dir: /app
    command: composer dumpautoload -o
  
  php-cli:
    image: php:8.1.26-cli-alpine3.18
    restart: "no"
    volumes:
      - ./app:/app
    working_dir: /app

  php-unit:
    image: php:8.1.26-cli-alpine3.18
    restart: "no"
    depends_on:
      composer-phpunit:
        condition: service_completed_successfully
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit

  fpm:
    image: php:8.1.26-fpm-alpine3.18
    restart: unless-stopped
    depends_on:
      composer-phpunit:
        condition: service_completed_successfully
    volumes:
      - ./app/src:/var/www/html
    working_dir: /app

  # nginx
  web:
    image: nginx:1.25.3
    restart: unless-stopped
    depends_on:
      - fpm
    ports:
      - "80:80"
    volumes:
      - ./app/src:/var/www/html
      - ./var/log/nginx:/var/log/nginx
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  # mysql
  # redis